# Generated by Django 5.2.1 on 2025-05-13 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0004_alter_loja_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.PositiveIntegerField(default=0)),
                (
                    "loja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="cadastro.loja",
                    ),
                ),
            ],
        ),
    ]
