# Generated by Django 4.2.7 on 2025-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='lojas/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
