# Generated by Django 5.2.1 on 2025-05-29 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluguel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefoneFixo", models.CharField(max_length=20)),
                ("telefoneCelular", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="FaleConosco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("assunto", models.CharField(max_length=1000)),
                (
                    "motivoContato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siteweb.motivocontato",
                    ),
                ),
            ],
        ),
    ]
